// workerd process management: generate config → spawn → health check → exit alongside the kernel.
//
//   Kernel (Node) ──spawn──▶ workerd (entry worker = overseer + AppStore DO)
//     ▲   NODE external-service binding (loops back to 127.0.0.1:<kernelPort>, the execution endpoint for syscalls)
//     │   The kernel in turn calls workerd's /_wd/* (the internal route for app data), authenticated with the WD_INTERNAL token
//     └── The shell's iframe points at http://<token>.localhost:<appPort>/ —— each app gets a real origin of its own
//
// App data (env.DB) lives in workerd's own SQLite: <workspace>/.wandesk/store/<STORE_KEY>/<objectId>.sqlite.
// If it fails to start, it doesn't take the kernel down with it —— apps just become unavailable, and the shell keeps
// showing normally with a notice.
import { spawn, type ChildProcess } from "child_process";
import { randomBytes } from "crypto";
import fs from "fs";
import net from "net";
import path from "path";
import { HOME, kernelDir } from "../kernel/paths.js";

let child: ChildProcess | null = null;
let origin: string | null = null;
let port: number | null = null;
let internalToken = "";

/** The AppStore namespace's uniqueKey: object IDs are derived from it — **change it and old data becomes unreachable**. Also doubles as the storage subdirectory name. */
export const STORE_KEY = "wandesk-app-store-v1";

/** The root directory for app data (workerd's localDisk). */
export const storeDir = () => {
  const dir = path.join(kernelDir(), "store");
  fs.mkdirSync(dir, { recursive: true });
  return dir;
};

/** The SQLite file a given AppStore object is written to on disk. Ask overseer for the object ID (/_wd/db/id). */
export const storeFile = (storeId: string) => path.join(storeDir(), STORE_KEY, `${storeId}.sqlite`);

const workerdBin = () => {
  if (process.env.WANDESK_WORKERD) return process.env.WANDESK_WORKERD;
  const platform = `${process.platform}-${process.arch}`;
  const packaged = path.join(HOME, "runtime/bin", process.platform === "win32" ? "workerd.exe" : "workerd");
  if (fs.existsSync(packaged)) return packaged;
  return path.join(HOME, `node_modules/@cloudflare/workerd-${platform}/bin/workerd`); // dev mode
};

const overseerBundle = () => process.env.WANDESK_OVERSEER || path.join(HOME, "dist/overseer.js");

const pickPort = () => new Promise<number>((resolve, reject) => {
  const probe = net.createServer();
  probe.once("error", reject);
  probe.listen(0, "127.0.0.1", () => {
    const address = probe.address();
    const port = typeof address === "object" && address ? address.port : 0;
    probe.close(() => resolve(port));
  });
});

const buildConfig = (kernelPort: number, runtimePort: number, store: string, token: string) => `# Generated by Wandesk at startup, do not edit by hand (runtime/supervisor.ts)
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    ( name = "overseer",
      worker = (
        modules = [ ( name = "overseer.js", esModule = embed "overseer.js" ) ],
        compatibilityDate = "2026-02-01",
        # Home of env.DB: one AppStore object per app, SQLite lands in the store directory service below
        durableObjectNamespaces = [ ( className = "AppStore", uniqueKey = "${STORE_KEY}", enableSql = true ) ],
        durableObjectStorage = ( localDisk = "store" ),
        bindings = [
          ( name = "LOADER", workerLoader = ( id = "apps" ) ),
          ( name = "NODE", service = "node" ),
          ( name = "STORE", durableObjectNamespace = "AppStore" ),
          ( name = "WD_INTERNAL", text = "${token}" ),
        ],
      )
    ),
    ( name = "node", external = ( address = "127.0.0.1:${kernelPort}" ) ),
    ( name = "store", disk = ( path = ${JSON.stringify(store)}, writable = true ) ),
  ],
  sockets = [ ( name = "http", address = "127.0.0.1:${runtimePort}", http = (), service = "overseer" ) ]
);
`;

const waitHealthy = async (port: number, timeoutMs = 10000) => {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/health`, { signal: AbortSignal.timeout(1000) });
      if (res.ok) return true;
    } catch { /* not up yet */ }
    if (child && child.exitCode !== null) return false;
    await new Promise((r) => setTimeout(r, 150));
  }
  return false;
};

export const startRuntime = async (kernelPort: number) => {
  try {
    const bin = workerdBin();
    const bundle = overseerBundle();
    if (!fs.existsSync(bin)) { console.log(`[runtime] workerd not found (${bin}), apps unavailable`); return; }
    if (!fs.existsSync(bundle)) { console.log("[runtime] overseer build output not found, run npm run build:overseer first"); return; }

    // Generated files go into the workspace, **never into the install directory** —— a packaged .app
    // can end up in a read-only location (/Applications, a mounted dmg, a quarantined Downloads
    // folder), and writing into the bundle there would simply fail to start.
    const dir = path.join(kernelDir(), "runtime");
    fs.mkdirSync(dir, { recursive: true });
    fs.copyFileSync(bundle, path.join(dir, "overseer.js"));

    const appPort = await pickPort();
    internalToken = randomBytes(24).toString("hex"); // A fresh token every startup, living only in memory and in this config file
    const configPath = path.join(dir, "workerd.capnp");
    fs.writeFileSync(configPath, buildConfig(kernelPort, appPort, storeDir(), internalToken), { mode: 0o600 });

    child = spawn(bin, ["serve", configPath, "--experimental"], { stdio: ["ignore", "pipe", "pipe"] });
    child.stdout?.setEncoding("utf8");
    child.stderr?.setEncoding("utf8");
    child.stdout?.on("data", (c: string) => process.stdout.write(`[workerd] ${c}`));
    child.stderr?.on("data", (c: string) => process.stderr.write(`[workerd] ${c}`));
    child.on("exit", (code) => {
      if (origin) console.error(`[runtime] workerd exited (code ${code}), apps unavailable`);
      child = null; origin = null;
    });

    if (await waitHealthy(appPort)) {
      origin = `http://127.0.0.1:${appPort}`;
      port = appPort;
      console.log(`[runtime] App runtime ready: ${origin}`);
    } else {
      console.error("[runtime] workerd failed to start, apps unavailable");
      try { child?.kill("SIGTERM"); } catch { /* already exited */ }
    }
  } catch (e: any) {
    console.error("[runtime] Startup error:", e?.message);
  }
};

/** The shell uses this to build each app's iframe URL. null = runtime unavailable. */
export const runtimeOrigin = () => origin;
/** An app's origin is `<token>.localhost:<port>` —— the port comes from here. */
export const runtimePort = () => port;
/** The token the kernel sends when calling workerd's internal route (/_wd/*). */
export const runtimeToken = () => internalToken;

export const stopRuntime = () => {
  origin = null; port = null;
  if (child) { try { child.kill("SIGTERM"); } catch { /* already exited */ } child = null; }
};

process.on("exit", stopRuntime);
process.on("SIGTERM", () => { stopRuntime(); process.exit(0); });
process.on("SIGINT", () => { stopRuntime(); process.exit(0); });
