// reader —— generated by build.mjs; editing this file directly will be overwritten by the next build.
// Frontend source lives in src/; after editing, run `npm run build`.
//
// The app is its own website: static assets and API are both served by it. The three APIs are
// carried over from the host capabilities in wandesk-skill, now wired to their own bindings —
// the app frontend code itself is unchanged.
const SCHEMA = "-- Reader —— each book is a continuable, reopenable interactive story\n-- Continuation relies on the engine's native multi-turn memory: conversation_id keeps the live session; pages are the fallback rebuild source if it goes stale.\n\nCREATE TABLE IF NOT EXISTS app_reader_books (\n  id              INTEGER PRIMARY KEY AUTOINCREMENT,\n  title           TEXT NOT NULL DEFAULT 'Untitled',  -- the title the AI gave the book\n  premise         TEXT NOT NULL DEFAULT '',          -- the setup the user gave (genre + opening)\n  conversation_id TEXT,                              -- engine session id, used for native continuation\n  status          TEXT NOT NULL DEFAULT 'ongoing',   -- 'ongoing' | 'ended'\n  created_at      TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\n-- Each page: a block of narrative + the choice the player made on this page (chosen is empty on the last page)\n-- The last page also stores \"the pending choices offered on this page\" in choices (JSON), so reopening at a decision point can resume directly.\nCREATE TABLE IF NOT EXISTS app_reader_pages (\n  id         INTEGER PRIMARY KEY AUTOINCREMENT,\n  book_id    INTEGER NOT NULL,\n  idx        INTEGER NOT NULL,                       -- page index, starting at 0\n  narrative  TEXT NOT NULL DEFAULT '',               -- this page's prose\n  chosen     TEXT NOT NULL DEFAULT '',               -- the action the player took to leave this page\n  choices    TEXT NOT NULL DEFAULT '[]',             -- the pending choices offered on this page (JSON array), used to restore the decision point\n  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\nCREATE INDEX IF NOT EXISTS app_reader_idx_pages_book ON app_reader_pages (book_id, idx);\n";

let ready = false;
const ensure = async (env) => {
  if (ready) return;
  if (SCHEMA) await env.DB.exec(SCHEMA);
  ready = true;
};

const json = (data, status = 200) =>
  new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8" } });

export default {
  async fetch(req, env) {
    const url = new URL(req.url);
    if (!url.pathname.startsWith("/api/")) return env.ASSETS.fetch(req);

    try {
      // ── own database (D1) ──
      if (url.pathname === "/api/db") {
        await ensure(env);
        const { sql, params } = await req.json();
        const stmt = env.DB.prepare(String(sql || ""));
        const r = await (Array.isArray(params) && params.length ? stmt.bind(...params) : stmt).all();
        return json({ ok: true, rows: r.results, changes: r.meta?.changes ?? 0, lastInsertRowid: r.meta?.last_row_id ?? 0 });
      }

      // ── the single AI surface ──
      if (url.pathname === "/api/agent") {
        const { prompt, data, system, schema } = await req.json();
        const want = schema
          ? "\n\nOutput only JSON matching the JSON Schema below — no code fences, no explanation:\n" + JSON.stringify(schema)
          : "";
        const out = await env.AI.ask({
          summary: `reader:` + String(prompt || "").slice(0, 24),
          system: String(system || ""),
          prompt: String(prompt || "") + want,
          data,
        });
        if (!out.ok) return json({ ok: false, error: out.error });
        let parsed;
        if (schema) {
          try { parsed = JSON.parse(String(out.text).trim().replace(/^\`\`\`[a-z]*\n?|\`\`\`$/g, "")); } catch { /* model did not return valid JSON */ }
        }
        return json({ ok: true, result: out.text, json: parsed, engine: "wandesk" });
      }

      // ── outbound network: full capability, backend fetches directly ──
      if (url.pathname === "/api/http") {
        const { url: target, method, headers, body } = await req.json();
        const res = await fetch(String(target), { method: method || "GET", headers, body });
        return json({ ok: res.ok, status: res.status, body: await res.text() });
      }

      return json({ ok: false, error: "not found" }, 404);
    } catch (e) {
      return json({ ok: false, error: String(e?.message || e) });
    }
  },
};
