// 飞机大战 — 界面文案(HUD 也是画在 canvas 上的,统一走这里)。
export const T = {
  title: '飞机大战',
  subtitle: 'N E O N   S K I E S',
  start: '开始游戏',
  startHint: '[ ENTER ] 开始',
  howtoTitle: '操作说明',
  howtoMove: '方向键 / WASD  移动',
  howtoFire: '空格 / 鼠标  开火',
  howtoAuto: '持续射击 · 拾取增益',
  howtoPause: 'P / ESC  暂停',
  clickFocus: '点击窗口以激活键盘',
  hiscore: '最高分',
  hudScore: '得分',
  hudWave: '波次',
  hudCombo: '连击',
  ready: '准备',
  go: '出击!',
  waveLabel: '第',
  waveSuffix: '波',
  warning: '警告',
  bossIncoming: '首领来袭',
  paused: '已暂停',
  resume: '继续游戏',
  resumeHint: '[ P ] 继续',
  restart: '重新开始',
  gameover: '任务失败',
  victory: '全数歼灭',
  finalScore: '最终得分',
  maxCombo: '最高连击',
  reachedWave: '抵达波次',
  newRecord: '★ 新纪录 ★',
  again: '再来一局',
  againHint: '[ ENTER ] 再来一局',
  puSpread: '散射火力!',
  puRapid: '极速连射!',
  puShield: '护盾启动!',
  puBomb: '全屏轰炸!',
  puHeal: '生命 +1',
  tagSpread: '散射',
  tagRapid: '连射',
  tagShield: '护盾',
  perfect: '完美通关!',
};
