// Aircraft — UI copy (the HUD is also drawn on canvas, so it all lives here too).
export const T = {
  title: 'AIRCRAFT',
  subtitle: 'N E O N   S K I E S',
  start: 'START GAME',
  startHint: '[ ENTER ] START',
  howtoTitle: 'CONTROLS',
  howtoMove: 'ARROWS / WASD  MOVE',
  howtoFire: 'SPACE / MOUSE  FIRE',
  howtoAuto: 'AUTO-FIRE · COLLECT POWER-UPS',
  howtoPause: 'P / ESC  PAUSE',
  clickFocus: 'Click the window to enable keyboard',
  hiscore: 'HIGH SCORE',
  hudScore: 'SCORE',
  hudWave: 'WAVE',
  hudCombo: 'COMBO',
  ready: 'READY',
  go: 'GO!',
  waveLabel: 'WAVE',
  waveSuffix: '',
  warning: 'WARNING',
  bossIncoming: 'BOSS INCOMING',
  paused: 'PAUSED',
  resume: 'RESUME',
  resumeHint: '[ P ] RESUME',
  restart: 'RESTART',
  gameover: 'MISSION FAILED',
  victory: 'ALL CLEAR',
  finalScore: 'FINAL SCORE',
  maxCombo: 'MAX COMBO',
  reachedWave: 'WAVE REACHED',
  newRecord: '★ NEW RECORD ★',
  again: 'PLAY AGAIN',
  againHint: '[ ENTER ] PLAY AGAIN',
  puSpread: 'SPREAD SHOT!',
  puRapid: 'RAPID FIRE!',
  puShield: 'SHIELD UP!',
  puBomb: 'SCREEN BOMB!',
  puHeal: '+1 LIFE',
  tagSpread: 'SPREAD',
  tagRapid: 'RAPID',
  tagShield: 'SHIELD',
  perfect: 'PERFECT CLEAR!',
};
